Update waka-readme.yml

diff --git a/.github/workflows/waka-readme.yml b/.github/workflows/waka-readme.yml
--- a/.github/workflows/waka-readme.yml
+++ b/.github/workflows/waka-readme.yml
@@ -8,27 +8,39 @@ on:
 permissions:
   contents: write
 
+env:
+  TARGET_BRANCH: main
+  TARGET_PATH: README.md
+
 jobs:
   update-readme:
     name: WakaReadme DevMetrics
     runs-on: ubuntu-latest
     steps:
-      - uses: athul/waka-readme@master # do NOT replace with anything else
+      - name: Check Wakatime API Key
+        run: |
+          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
+            echo "WAKATIME_API_KEY is not set"; exit 1
+          fi
+
+      - uses: athul/waka-readme@master
         with:
-          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
-          ### content
-          SHOW_TITLE: true # optional
-          SECTION_NAME: waka # optional
-          BLOCKS: -> # optional
-          TIME_RANGE: all_time # optional
-          LANG_COUNT: 10 # optional
-          SHOW_TIME: true # optional
-          SHOW_TOTAL: true # optional
-          SHOW_MASKED_TIME: false # optional
-          STOP_AT_OTHER: true # optional
-          IGNORED_LANGUAGES: YAML JSON TOML # optional
-          ### commit
-          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
-          TARGET_PATH: README.md # optional
-          COMMITTER_NAME: GitHubActionBot # optional
+          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
+          SHOW_TITLE: true
+          SECTION_NAME: waka
+          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
+          TIME_RANGE: all_time
+          LANG_COUNT: 10
+          SHOW_TIME: true
+          SHOW_TOTAL: true
+          SHOW_MASKED_TIME: false
+          STOP_AT_OTHER: true
+          COMMIT_MESSAGE: "Updated waka-readme graph: ${{ github.run_id }} on ${{ github.run_attempt }} [${{ github.workflow }}]"
+          TARGET_PATH: ${{ env.TARGET_PATH }}
           COMMITTER_EMAIL: action-bot@github.com
+          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
+
+      - name: Notify on failure
+        if: failure()
+        run: |
+          echo "The workflow has failed."
